---
# source: palisade/templates/configure-services.yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: configure-example
  name: configure-example
spec:
  template:
    spec:
      containers:
        - image: example_configure-example:latest
          name: configure-example
          imagePullPolicy: Never
          command: ["/tmp/waitForHost.sh", "http://policy-service:8080/policy/v1/status", "/tmp/waitForHost.sh", "http://config-service:8080/config/v1/status", "/tmp/waitForHost.sh", "http://data-service:8080/data/v1/status", "/tmp/waitForHost.sh", "http://user-service:8080/user/v1/status", "/tmp/waitForHost.sh", "http://palisade-service:8080/palisade/v1/status", "java", "-cp", "/tmp/example-model-*-shaded.jar", "-Dpalisade.rest.config.path=/tmp/configRest.json", "uk.gov.gchq.palisade.example.config.ExampleConfigurator", "/data"]
      restartPolicy: Never