language: java
cache:
  timeout: 1000
  directories:
  - $HOME/.m2
dist: trusty
jdk:
  - oraclejdk8
sudo: false

install: travis_wait 45 ./cd/install.sh
script:
  - travis_wait 45 ./cd/verify.sh
  - ./cd/deploy.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: _book
  on:
    branch: master

before_cache: rm -rf $HOME/.m2/repository/uk/gov/gchq/palisade
