---
# Source: palisade/templates/configure-services.yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: configure-services
  name: configure-services
spec:
  template:
    spec:
      containers:
        - image: palisadeacr.azurecr.io/configure-services:latest
          name: configure-services
          command: ["/tmp/waitForHost.sh", "http://config-service:8080/config/v1/status", "java", "-cp", "/tmp/example-model-*-shaded.jar", "uk.gov.gchq.palisade.example.config.DistributedServices", "FALSE", "http://palisade-service:8080/palisade", "http://policy-service:8080/policy", "http://resource-service:8080/resource", "http://user-service:8080/user", "http://data-service:8080/data", "http://config-service:8080/config", "http://palisade-service/palisade", "http://data-service/data"]
      restartPolicy: Never