---
# Source: palisade/template-data-service.yaml
kind: Service
apiVersion: v1
metadata:
  labels:
    app: data-service
  name: data-service
spec:
  type: LoadBalancer
  selector:
    app: data-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# Source: palisade/templates/data-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:  data-service
  name: data-service
spec:
  replicas: {{ .Values.data-service.replicas }}
  selector:
    matchLabels:
      app:  data-service
  template:
    metadata:
      labels:
        app:  data-service
    spec:
      containers:
      - image: "{{ .Values.data-service.image.repository }}:{{ .Values.data-service.image.tag }}"
        imagePullPolicy: "{{ .Values.data-service.image.pullPolicy }}"
        name: data-service
        livenessProbe:
          httpGet:
            path: /data/v1/status
            port: 8080
          failureThreshold: 5
          periodSeconds: 60
          timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /data/v1/status
              port: 8080
            failureThreshold: 5
            periodSeconds: 60
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.data-service.resources | nindent 12 }}
        volumeMounts:
          - name: data
            mountPath: /data
      restartPolicy: Always
      volumes:
      - name: data
        azureFile:
          secretName: data-share-secret
          shareName: data
          readOnly: true
