# Default values for palisade.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

configservice:
  image:
    pullPolicy: IfNotPresent
    repository: palisadeacr.azurecr.io/config-service
    tag: latest
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 0.5
      memory: 2Gi
  replicas: 1

dataservice:
  image:
    pullPolicy: Always
    repository: palisadeacr.azurecr.io/data-service
    tag: latest
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 0.5
      memory: 10Gi
  replicas: 1

etcd:
  image:
    pullPolicy: IfNotPresent
    repository: palisadeacr.azurecr.io/etcd
    tag: latest
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 0.25
      memory: 1Gi
  replicas: 1

palisadeservice:
  image:
    pullPolicy: IfNotPresent
    repository: palisadeacr.azurecr.io/palisade-service
    tag: latest
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 0.5
      memory: 2Gi
  replicas: 1

policyservice:
  image:
    pullPolicy: IfNotPresent
    repository: palisadeacr.azurecr.io/policy-service
    tag: latest
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 0.5
      memory: 2Gi
  replicas: 1

resourceservice:
  image:
    pullPolicy: IfNotPresent
    repository: palisadeacr.azurecr.io/resource-service
    tag: latest
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 0.5
      memory: 2Gi
  replicas: 1

userservice:
  image:
    pullPolicy: IfNotPresent
    repository: palisadeacr.azurecr.io/user-service
    tag: latest
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 0.5
      memory: 2Gi
  replicas: 1

configureexample:
  inputfilepath: /data

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
